(require 'rich-minority)
(add-to-list 'rm-excluded-modes " yas")
(add-to-list 'rm-excluded-modes " hl-s")
(add-to-list 'rm-excluded-modes " ElDoc")
(add-to-list 'rm-excluded-modes " Paredit")
(add-to-list 'rm-excluded-modes " SliNav")
(add-to-list 'rm-excluded-modes " SliExp")
(add-to-list 'rm-excluded-modes " SP")
(add-to-list 'rm-excluded-modes " ||")
(add-to-list 'rm-excluded-modes "/s")
