;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-hungry-delete-backwards
        helm-show-kill-ring
        hungry-delete-backward
        hungry-delete-forward
        keyboard-escape-quit
        kill-region
        mouse-set-region
        org-self-insert-command
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-open-round
        paredit-raise-sexp
        paredit-semicolon
        paredit-splice-sexp
        slime-space
        sp--self-insert-command
        sp-backward-kill-word
        sp-backward-slurp-sexp
        sp-delete-char
        sp-forward-slurp-sexp
        sp-kill-hybrid-sexp
        sp-kill-word
        sp-splice-sexp
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        ido-kill-buffer
        rs/buffers-list
        ))
